# Generated by Django 3.1.6 on 2021-03-04 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(default='No Description given'),
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.FilePathField(default='/img/noimage.png', path='/img'),
        ),
        migrations.AddField(
            model_name='project',
            name='technology',
            field=models.CharField(default='Django', max_length=50),
        ),
    ]
