# Generated by Django 3.1.6 on 2021-03-09 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_remove_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='img',
            field=models.ImageField(default='projects/noimg.jpg', upload_to='projects/'),
        ),
    ]
